In [20]:
import pandas as pd
import json

In [23]:

with open('t20_json_files\\t20_wc_match_results.json') as f:
    data = json.load(f)
df_match=pd.DataFrame(data[0]['matchSummary'])
df_match

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,South Africa,Zimbabwe,no result,,Hobart,"Oct 24, 2022",T20I # 1844
18,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,Afghanistan,New Zealand,abandoned,,Melbourne,"Oct 26, 2022",T20I # 1846a
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
23,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
24,Afghanistan,Ireland,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849a
25,Australia,England,abandoned,,Melbourne,"Oct 28, 2022",T20I # 1849b
26,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
27,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
28,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
29,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
30,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
31,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
32,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
33,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
34,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
35,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
36,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
37,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
38,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
39,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
40,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [24]:
df_match.shape

(45, 7)

In [27]:
df_match.rename({'scorecard':'match_id'},axis=1,inplace=True)
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

#bating summary

In [30]:
a=[2,3]
b=[5,6]
a.extend(b)
a

[2, 3, 5, 6]

In [34]:
with open('t20_json_files\\t20_wc_batting_summary.json') as f:
    data = json.load(f)

    all_records=[]
    for rec in data:
        all_records.extend(rec['battingSummary'])
df_batting = pd.DataFrame(all_records)
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09

In [37]:
df_batting["out/not_out"]=df_batting.dismissal.apply(lambda x:"out"if len(x)>0 else "not_out")
df_batting.head(11)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09,out